spring:
  profiles:
    activate:
      on-profile: local

  jpa:
    hibernate:
      ddl-auto: create

  aws:
    access-key: ${AWS_ACCESS_KEY_ID}
    secret-key: ${AWS_SECRET_ACCESS_KEY}
    session-token: ${AWS_SESSION_TOKEN}