spring:
  profiles:
    activate:
      on-profile: local

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.xml

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: false


  sql:
    init:
      mode: always
      data-locations: classpath:import.sql

  aws:
    access-key: ${AWS_ACCESS_KEY_ID}
    secret-key: ${AWS_SECRET_ACCESS_KEY}
    session-token: ${AWS_SESSION_TOKEN}
logging:
  level:
    org:
      springframework:
        messaging: trace
        web:
          socket: trace
translation:
  api-key: ${DEEPL_TRANSLATE_API_KEY}