spring:
  profiles:
    activate:
      on-profile: local

  jpa:
    open-in-view: true

  sql:
    init:
      mode: never
      data-locations: classpath:import.sql

  aws:
    access-key: ${AWS_ACCESS_KEY_ID}
    secret-key: ${AWS_SECRET_ACCESS_KEY}
    session-token: ${AWS_SESSION_TOKEN}
logging:
  level:
    org:
      springframework:
        messaging: trace
        web:
          socket: trace
translation:
  api-key: ${DEEPL_TRANSLATE_API_KEY}