spring:
    jpa:
        database-platform: org.hibernate.dialect.MySQLDialect
        open-in-view: false
        show-sql: true
        hibernate:
            ddl-auto: update
        defer-datasource-initialization: true

    sql:
        init:
            mode: always
            data-locations: classpath:import.sql

    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?
        username: ${DB_USER}
        password: ${DB_PASSWORD}

    mail:
        host: smtp.gmail.com
        port: 587
        username: ${GOOGLE_EMAIL}
        password: ${GOOGLE_APP_PASSWORD}
        properties:
          mail:
              smtp:
                  starttls:
                      enable: true
                      auth: true

    aws:
        region: ${AWS_REGION_CODE}
        bucket-name: ${AWS_S3_BUCKET_NAME}

    data:
        redis:
            host: ${REDIS_HOST}
            port: ${REDIS_PORT}

jwt:
    secret: ${JWT_SECRET}

management:
    health:
        mail:
            enabled: false
    endpoints:
        web:
         base-path: /

springdoc:
    swagger-ui:
        groups-order: DESC
        tags-sorter: alpha
        operations-sorter: method
        disable-swagger-default-url: true
        display-request-duration: true
        default-models-expand-depth: -1
        default-model-expand-depth: -1
    api-docs:
      path: /api/v1/api-docs
    show-actuator: true
    writer-with-default-pretty-printer: true
    model-and-view-allowed: true
    paths-to-match:
        - /api/**
