package com.diverse.dife.entity.schoolInfo.building;

public enum Category {
    ADMINISTRATION_HALL,
    BUGAK_HALL,
    COLLEGE_OF_ENGINEERING,
    COLLEGE_OF_LAW,
    COLLEGE_OF_SCIENCE,
    COLLEGE_OF_DESIGN,
    GYMNASIUM,
    SUNGKOK_LIBRARY,
    HYUNGSUL_HALL,
    COLLEGEG_OF_ECONOMICS_AND_COMMERCE,
    INTERNATIONAL_HALL,
    COLLEGE_OF_BUSINESS_ADMINISTRATION,
    COLLEGE_OF_ARTS,
    MIRAE_HALL,
    STUDENT_UNION,
    INNOVATION_PARTNERSHIP_BUILDING,
    GLOBAL_CENTER,
    LIFELONG_EDUCATION_PRACTICAL_BULDING,
    DORMITORY,
    PLAYING_FIELD,
    YONDURI,
    MAIN_GATE,
    REAR_GATE,
    TENNIS_COURT
}
