spring:
    profiles:
        active: local

    jpa:
        database-platform: org.hibernate.dialect.MySQLDialect
        open-in-view: false
        show-sql: true
        hibernate:
            ddl-auto: create
    mail:
        host: smtp.gmail.com
        port: 587
        username: ${GOOGLE_EMAIL}
        password: ${GOOGLE_APP_PASSWORD}
        properties:
          mail:
              smtp:
                  starttls:
                      enable: true
                      auth: true

jwt:
    secret : ${JWT_ACCESS_KEY}