name: Unit test

on: 
  pull_request:

jobs:
  test:
    name: JUnit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set Up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant Permission
        run: chmod +x gradlew

      - name: Test
        run: ./gradlew --info test